description: Prepares the repo for a typical CI job

name: Prepare

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Enable Corepack (Yarn v4)
      run: corepack enable
      shell: bash

    - name: Install dependencies
      run: yarn
      shell: bash
